"""Initial revision

Revision ID: 2f08d665a653
Revises: 52db15e05451
Create Date: 2025-10-25 17:01:11.757192

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2f08d665a653'
down_revision: Union[str, Sequence[str], None] = '52db15e05451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('price', sa.String(), nullable=True))
    op.drop_column('tasks', 'zp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('zp', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'price')
    # ### end Alembic commands ###
