"""Initial revision

Revision ID: 3a65d9be37a4
Revises: d9868d053262
Create Date: 2025-10-25 17:33:52.988756

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3a65d9be37a4'
down_revision: Union[str, Sequence[str], None] = 'd9868d053262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'uid_creator',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('projects', 'uid_client',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'uid_client',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('projects', 'uid_creator',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
