"""Initial revision

Revision ID: 52db15e05451
Revises: 9fc19fc90499
Create Date: 2025-10-25 16:59:59.638693

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '52db15e05451'
down_revision: Union[str, Sequence[str], None] = '9fc19fc90499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('uid_worker', sa.UUID(), nullable=False),
    sa.Column('uid_proj', sa.UUID(), nullable=False),
    sa.Column('permission_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uid_proj'], ['projects.uid'], ),
    sa.ForeignKeyConstraint(['uid_worker'], ['workers.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('subtasks',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('uid_task', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uid_task'], ['tasks.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_table('worker_projects')
    op.drop_table('clients_projects')
    op.add_column('projects', sa.Column('initial_budget', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('status', sa.String(), nullable=False))
    op.add_column('projects', sa.Column('deadline', sa.Date(), nullable=False))
    op.drop_constraint(op.f('_user_post_to_user'), 'projects', type_='unique')
    op.drop_column('projects', 'Initial_budget')
    op.add_column('workers', sa.Column('email', sa.String(), nullable=False))
    op.drop_constraint(op.f('67868767876678'), 'workers_tasks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('67868767876678'), 'workers_tasks', ['uid_task', 'uid_worker'], postgresql_nulls_not_distinct=False)
    op.drop_column('workers', 'email')
    op.add_column('projects', sa.Column('Initial_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('_user_post_to_user'), 'projects', ['uid_creator', 'uid_client'], postgresql_nulls_not_distinct=False)
    op.drop_column('projects', 'deadline')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'initial_budget')
    op.create_table('clients_projects',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uid_client', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uid_proj', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['uid_client'], ['clients.uid'], name=op.f('clients_projects_uid_client_fkey')),
    sa.ForeignKeyConstraint(['uid_proj'], ['projects.uid'], name=op.f('clients_projects_uid_proj_fkey')),
    sa.PrimaryKeyConstraint('uid', name=op.f('clients_projects_pkey')),
    sa.UniqueConstraint('uid_client', 'uid_proj', name=op.f('676777678'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('worker_projects',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uid_worker', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uid_proj', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['uid_proj'], ['projects.uid'], name=op.f('worker_projects_uid_proj_fkey')),
    sa.ForeignKeyConstraint(['uid_worker'], ['workers.uid'], name=op.f('worker_projects_uid_worker_fkey')),
    sa.PrimaryKeyConstraint('uid', name=op.f('worker_projects_pkey')),
    sa.UniqueConstraint('uid_worker', 'uid_proj', name=op.f('687867867876'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('subtasks')
    op.drop_table('permissions')
    # ### end Alembic commands ###
