"""Initial revision

Revision ID: 82262160af3a
Revises: 
Create Date: 2025-10-30 18:34:19.553941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82262160af3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('telephone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('workers',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('telephone_number', sa.String(), nullable=False),
    sa.Column('colour', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('projects',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.Column('uid_creator', sa.UUID(), nullable=True),
    sa.Column('uid_client', sa.UUID(), nullable=True),
    sa.Column('initial_budget', sa.Float(), nullable=True),
    sa.Column('result_budget', sa.Float(), nullable=True),
    sa.Column('colour', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['uid_client'], ['clients.uid'], ),
    sa.ForeignKeyConstraint(['uid_creator'], ['workers.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('permissions',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('uid_worker', sa.UUID(), nullable=False),
    sa.Column('uid_proj', sa.UUID(), nullable=False),
    sa.Column('permission_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uid_proj'], ['projects.uid'], ),
    sa.ForeignKeyConstraint(['uid_worker'], ['workers.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('tasks',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('uid_proj', sa.UUID(), nullable=False),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uid_proj'], ['projects.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('subtasks',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('uid_task', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uid_task'], ['tasks.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('workers_tasks',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('uid_task', sa.UUID(), nullable=False),
    sa.Column('uid_worker', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['uid_task'], ['tasks.uid'], ),
    sa.ForeignKeyConstraint(['uid_worker'], ['workers.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workers_tasks')
    op.drop_table('subtasks')
    op.drop_table('tasks')
    op.drop_table('permissions')
    op.drop_table('projects')
    op.drop_table('workers')
    op.drop_table('clients')
    # ### end Alembic commands ###
