"""Initial revision

Revision ID: c85affbea4bd
Revises: 87b0941ecf6c
Create Date: 2025-10-22 19:39:09.918505

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c85affbea4bd'
down_revision: Union[str, Sequence[str], None] = '87b0941ecf6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('telephone_number', sa.String(), nullable=False),
    sa.Column('colour', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('projects',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.Column('uid_creator', sa.UUID(), nullable=False),
    sa.Column('uid_client', sa.UUID(), nullable=False),
    sa.Column('Initial_budget', sa.Float(), nullable=True),
    sa.Column('result_budget', sa.Float(), nullable=True),
    sa.Column('colour', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uid_client'], ['clients.uid'], ),
    sa.ForeignKeyConstraint(['uid_creator'], ['workers.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('uid_creator', 'uid_client', name='_user_post_to_user')
    )
    op.create_table('clients_projects',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('uid_client', sa.UUID(), nullable=False),
    sa.Column('uid_proj', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['uid_client'], ['clients.uid'], ),
    sa.ForeignKeyConstraint(['uid_proj'], ['projects.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('uid_client', 'uid_proj', name='676777678')
    )
    op.create_table('tasks',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('uid_proj', sa.UUID(), nullable=False),
    sa.Column('zp', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uid_proj'], ['projects.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('worker_projects',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('uid_worker', sa.UUID(), nullable=False),
    sa.Column('uid_proj', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['uid_proj'], ['projects.uid'], ),
    sa.ForeignKeyConstraint(['uid_worker'], ['workers.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('uid_worker', 'uid_proj', name='687867867876')
    )
    op.create_table('workers_tasks',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('uid_task', sa.UUID(), nullable=False),
    sa.Column('uid_worker', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['uid_task'], ['tasks.uid'], ),
    sa.ForeignKeyConstraint(['uid_worker'], ['workers.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('uid_task', 'uid_worker', name='67868767876678')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workers_tasks')
    op.drop_table('worker_projects')
    op.drop_table('tasks')
    op.drop_table('clients_projects')
    op.drop_table('projects')
    op.drop_table('workers')
    # ### end Alembic commands ###
